### ISSUE TITLE
M2: Zero-Ball Autos

### ISSUE THREAD

**Issue by KilroyWasHere-cs-j** [frc5687/2022-robot#14]
Autos for the comp bot.

**Comment by greenermoose** [comment]
I think this is too vague for an issue branch. I'd like to see a separate for each auto milestone. First auto milestone is "Zero-ball taxi" which just moves the robot so its bumpers are completely out of the tarmac. Let's discuss.

**Comment by greenermoose** [comment]
This is [milestone 2 in Good Day](https://www.goodday.work/t/eFFunu).
