### ISSUE TITLE
ButtonMap

### ISSUE THREAD

**Issue by KilroyWasHere-cs-j** [frc5687/2022-robot#20]
Put button mappings in a separate file to make it easier to change which buttons map to which commands.

**Comment by BenBernardCIS** [comment]
Why a config file?  Why not include these in the constants file?

**Comment by KilroyWasHere-cs-j** [comment]
So people can change stuff like max MPS, accel, and other stuff without changing the code.

**Comment by BenBernardCIS** [comment]
Is the goal to account for different drivetrains between different robots?   Or to tweak settings in realtime?
If the former, you should consider using our "identity" modes.  If the latter, a config file is fine but smartdashboard settings might be easier.

**Comment by greenermoose** [comment]
Put all config settings and constants in the constants file so people can tune and test robot by editing just that one constants file, without having to edit classes or hunt down constants buried in other files.

**Comment by KilroyWasHere-cs-j** [comment]
All the basic configure stuff is in the constants folder already.

**Comment by KilroyWasHere-cs-j** [comment]
With the acception of the new subsystems.

**Comment by greenermoose** [comment]
We have two branches for this issue: Misc/#20-Constants and System/#20-ConfigFile. Can we delete the System/#20-ConfigFile branch?
